export const testimonials = [
  {
    name: "James Mitchell",
    role: "Senior HVAC Engineer · London",
    avatar: "JM",
    avatarBg: "bg-green-100",
    avatarText: "text-green-800",
    rating: 5,
    text: "This tool has completely transformed how our team handles HVAC calculations. What used to take hours now takes minutes. The accuracy is unmatched.",
    date: "2 weeks ago",
    featured: false,
  },
  {
    name: "Sarah Reynolds",
    role: "Mechanical Design Lead · Dubai",
    avatar: "SR",
    avatarBg: "bg-emerald-100",
    avatarText: "text-emerald-800",
    rating: 5,
    text: "The duct sizing calculator is incredibly accurate. I've verified results against manual calculations and they match perfectly every single time.",
    date: "1 month ago",
    featured: true,
  },
  {
    name: "Ali Khan",
    role: "Building Services Consultant · Sydney",
    avatar: "AK",
    avatarBg: "bg-orange-100",
    avatarText: "text-orange-800",
    rating: 5,
    text: "Finally a platform that understands what engineers need. Clean UI, fast calculations, no unnecessary complexity. Our whole team switched within a week.",
    date: "3 weeks ago",
    featured: false,
  },
  {
    name: "Laura Torres",
    role: "HVAC Project Manager · Toronto",
    avatar: "LT",
    avatarBg: "bg-blue-100",
    avatarText: "text-blue-800",
    rating: 4,
    text: "The refrigerant charge calculator alone is worth it. Reduced commissioning errors on our last three projects significantly.",
    date: "1 week ago",
    featured: false,
  },
];
